First we remove the ugly sum(..) call in the inner loop. The performance should be the same though, since that one just indexes one array element. And indeed it is. I've also added some static imports to make the code look a bit better. Too much Math can be intimidating to some. I've also lowered the number of iterations for the complexity calculation so we don't spend too much time running tests.
java.lang.AssertionError: The complexity should be close to N (which is N^1) ~ 1
Expected: is <1L>
     but: was <3L>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    ...